language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

before_install:
  - sudo apt-get update > /dev/null
  - composer self-update
  - composer install -n --prefer-source

install:
  - sudo apt-get install -y --force-yes php5-cgi php5-curl
  - phpenv rehash

before_script:
  - mkdir -p $TRAVIS_BUILD_DIR/build/logs

script:
  - $TRAVIS_BUILD_DIR/vendor/bin/phpunit --coverage-clover $TRAVIS_BUILD_DIR/build/logs/clover.xml --verbose --debug

after_script:
  - cd $TRAVIS_BUILD_DIR
  - php $TRAVIS_BUILD_DIR/vendor/bin/coveralls -v
  - $TRAVIS_BUILD_DIR/vendor/bin/phpmd $TRAVIS_BUILD_DIR text codesize,naming,design
  - $TRAVIS_BUILD_DIR/vendor/bin/phpcpd $TRAVIS_BUILD_DIR
  - $TRAVIS_BUILD_DIR/vendor/bin/phpcs --standard=$TRAVIS_BUILD_DIR/vendor/drupal/coder/coder_sniffer/Drupal $TRAVIS_BUILD_DIR

after_failure:
  - sudo cat /var/log/syslog

notifications:
  irc: irc.freenode.org#vmdoh
